// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web/user.proto

/*
Package web is a generated protocol buffer package.

It is generated from these files:
	web/user.proto

It has these top-level messages:
	CreateUserRequest
	CreateUserResponse
*/
package web

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserRequest struct {
	Nickname string `protobuf:"bytes,1,opt,name=Nickname" json:"Nickname,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Surname  string `protobuf:"bytes,3,opt,name=Surname" json:"Surname,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateUserRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

type CreateUserResponse struct {
	ID        string                     `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Nickname  string                     `protobuf:"bytes,2,opt,name=Nickname" json:"Nickname,omitempty"`
	Name      string                     `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Surname   string                     `protobuf:"bytes,4,opt,name=Surname" json:"Surname,omitempty"`
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateUserResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CreateUserResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserResponse) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *CreateUserResponse) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "web.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "web.CreateUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := grpc.Invoke(ctx, "/web.UserService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/web.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "web.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web/user.proto",
}

func init() { proto.RegisterFile("web/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4f, 0x4d, 0xd2,
	0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x4f, 0x4d, 0x92,
	0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x25, 0x95, 0xa6, 0xe9, 0x97, 0x64,
	0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x54, 0x49, 0xc9, 0x40, 0x15, 0x24, 0x16, 0x64,
	0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x64, 0x95, 0x62,
	0xb9, 0x04, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x43, 0x8b, 0x53, 0x8b, 0x82, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0xfc, 0x32, 0x93, 0xb3, 0xf3, 0x12, 0x73, 0x53, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x21, 0x2e, 0x16, 0x3f, 0x90, 0x38, 0x13,
	0x58, 0x1c, 0xcc, 0x16, 0x92, 0xe0, 0x62, 0x0f, 0x2e, 0x2d, 0x02, 0x2b, 0x67, 0x06, 0x0b, 0xc3,
	0xb8, 0x4a, 0x2b, 0x18, 0xb9, 0x84, 0x90, 0xcd, 0x2f, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0xe2,
	0xe3, 0x62, 0xf2, 0x74, 0x81, 0x1a, 0xcd, 0xe4, 0xe9, 0x82, 0x62, 0x21, 0x13, 0x0e, 0x0b, 0x99,
	0xb1, 0x5b, 0xc8, 0x82, 0x62, 0xa1, 0x90, 0x05, 0x17, 0x27, 0xc4, 0xbe, 0x14, 0xc7, 0x12, 0x09,
	0x56, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x29, 0x3d, 0x48, 0x08, 0xe8, 0xc1, 0x82, 0x48, 0x2f, 0x04,
	0x16, 0x44, 0x41, 0x08, 0xc5, 0x46, 0x49, 0x5c, 0xdc, 0x20, 0x37, 0x06, 0xa7, 0x16, 0x95, 0x65,
	0x26, 0xa7, 0x0a, 0x05, 0x73, 0x71, 0x21, 0x1c, 0x2e, 0x24, 0xa6, 0x57, 0x9e, 0x9a, 0xa4, 0x87,
	0x11, 0x52, 0x52, 0xe2, 0x18, 0xe2, 0x10, 0x1f, 0x2a, 0x89, 0x34, 0x5d, 0x7e, 0x32, 0x99, 0x89,
	0x4f, 0x89, 0x53, 0xbf, 0xcc, 0x10, 0x1c, 0x67, 0xc5, 0x56, 0x8c, 0x5a, 0x49, 0x6c, 0x60, 0x27,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x10, 0xfa, 0x65, 0x32, 0xca, 0x01, 0x00, 0x00,
}
